class Tx:
    GROUP_DELIMITER_COMMENT_INDICATOR_TEXT = "TEMPLATE GROUP TITLE"
    TEMPLATE_SPACER_COMMENT_INDICATOR_TEXT = "TEMPLATE SPACER"
    MARK_HEADERS = "MARK: HEADERS"
    START_SUFFIX = ": START"
    END_SUFFIX = ": END"
    DUMMY_SPACING = "DUMMY SPACING"
    COMMENT_TAG_STARTING = "<!--"
    COMMENT_TAG_ENDING = "-->"